# Generated by Django 4.2.1 on 2023-05-26 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0003_alter_personagem_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Madeiras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Descrição da Madeira', max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Nucleos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Descrição do Núcleo', max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Tamanhos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do Tamanho', max_length=1, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(help_text='Descrição do Tamanho', max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.AlterField(
            model_name='casa',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID_Casa'),
        ),
        migrations.AlterField(
            model_name='varinha',
            name='madeira',
            field=models.ForeignKey(help_text='Madeira da Varinha', on_delete=django.db.models.deletion.CASCADE, to='hogwarts.madeiras', verbose_name='Madeira'),
        ),
        migrations.AlterField(
            model_name='varinha',
            name='nucleo',
            field=models.ForeignKey(help_text='Núcleo da Varinha', on_delete=django.db.models.deletion.CASCADE, to='hogwarts.nucleos', verbose_name='Núcleo'),
        ),
        migrations.AlterField(
            model_name='varinha',
            name='tamanho',
            field=models.ForeignKey(help_text='Tamanho da Varinha', on_delete=django.db.models.deletion.CASCADE, to='hogwarts.tamanhos', verbose_name='Tamanho'),
        ),
    ]
