# Generated by Django 4.2.1 on 2023-05-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0005_rename_madeiras_madeira_rename_nucleos_nucleo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Imagem do Personagem', max_length=200, null=True, upload_to='media/', verbose_name='Logo da Casa'),
        ),
        migrations.AlterField(
            model_name='madeira',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nucleo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='nome',
            field=models.CharField(help_text='Nome do Tamanho', max_length=3, unique=True, verbose_name='Nome'),
        ),
    ]
