# Generated by Django 4.2.1 on 2023-05-26 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hogwarts', '0010_alter_aluno_casa_alter_aluno_varinha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuário do Aluno', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
