# Generated by Django 4.2.1 on 2023-05-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0011_alter_aluno_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='animal',
            field=models.ForeignKey(default=3, help_text='Animal do Aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='hogwarts.animal', verbose_name='Animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='casa',
            field=models.ForeignKey(default=1, help_text='Casa do Aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='hogwarts.casa', verbose_name='Casa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(help_text='Nome do Aluno', max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='varinha',
            field=models.ForeignKey(help_text='Varinha do Aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='hogwarts.varinha', verbose_name='Varinha'),
        ),
    ]
