# Generated by Django 4.2 on 2023-05-15 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID_Animal')),
                ('nome', models.CharField(help_text='Nome do Animal', max_length=255, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(help_text='Descrição do Animal', max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID_Casa')),
                ('nome', models.CharField(help_text='Nome da Casa', max_length=255, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Varinha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID_Varinha')),
                ('descricao', models.CharField(help_text='Descrição da Varinha', max_length=255, verbose_name='Descrição')),
                ('madeira', models.CharField(choices=[('Carvalho', 'Carvalho'), ('Salgueiro', 'Salgueiro'), ('Teixo', 'Teixo'), ('Faia', 'Faia')], default='Carvalho', help_text='Madeira da Varinha', max_length=20, verbose_name='Madeira')),
                ('nucleo', models.CharField(choices=[('Pelo de Unicórnio', 'Pelo de Unicórnio'), ('Pelo de Dragão', 'Pelo de Dragão'), ('Pelo de Fênix', 'Pelo de Fênix'), ('Pelo de Veela', 'Pelo de Veela')], default='Pelo de Fênix', help_text='Núcleo da Varinha', max_length=30, verbose_name='Núcleo')),
                ('tamanho', models.CharField(choices=[('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande'), ('E', 'Enorme')], default='M', help_text='Tamanho da Varinha', max_length=255, verbose_name='Tamanho')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID_Aluno')),
                ('nome', models.CharField(help_text='Nome do Aluno', max_length=255, verbose_name='Nome')),
                ('animal', models.ForeignKey(help_text='Animal do Aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='hogwarts.animal', verbose_name='Animal')),
                ('casa', models.ForeignKey(help_text='Casa do Aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='hogwarts.casa', verbose_name='Casa')),
                ('usuario', models.OneToOneField(help_text='Usuário do Aluno', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('varinha', models.ForeignKey(help_text='Varinha do Aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='hogwarts.varinha', verbose_name='Varinha')),
            ],
        ),
    ]
