# Generated by Django 4.2 on 2023-05-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Personagem', max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(help_text='Descrição do Personagem', max_length=2048, verbose_name='Descrição')),
                ('imagem', models.ImageField(help_text='Imagem do Personagem', upload_to='media/', verbose_name='Imagem')),
            ],
        ),
    ]
