# Generated by Django 4.2 on 2023-05-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0002_personagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='nome',
            field=models.CharField(help_text='Nome do Personagem', max_length=255, unique=True, verbose_name='Nome'),
        ),
    ]
