# Generated by Django 4.2.1 on 2023-05-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0004_madeiras_nucleos_tamanhos_alter_casa_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Madeiras',
            new_name='Madeira',
        ),
        migrations.RenameModel(
            old_name='Nucleos',
            new_name='Nucleo',
        ),
        migrations.RenameModel(
            old_name='Tamanhos',
            new_name='Tamanho',
        ),
    ]
