# Generated by Django 4.2.1 on 2023-05-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0008_alter_animal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='animal',
            field=models.ForeignKey(blank=True, help_text='Animal do Aluno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hogwarts.animal', verbose_name='Animal'),
        ),
    ]
