# Generated by Django 4.2.1 on 2023-05-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0009_alter_aluno_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='casa',
            field=models.ForeignKey(blank=True, help_text='Casa do Aluno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hogwarts.casa', verbose_name='Casa'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='varinha',
            field=models.ForeignKey(blank=True, help_text='Varinha do Aluno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hogwarts.varinha', verbose_name='Varinha'),
        ),
    ]
